version: '2'
# Dev config, mounts from host directory, depends on prod.yml

services:
  app:
    build: {}
    image: ${PHP_IMAGE}
    volumes:
     - ${COMPOSE_DIR}/../../:/var/www
     - ${COMPOSER_HOME}:/root/.composer
